[general]
import = [ 
     "~/.config/alacritty/themes/themes/tokyo_night.toml"
     ]
[cursor]
style = "Beam"
unfocused_hollow = true

[font]
normal = { family = "Hack", style = "Medium"}
bold = { family = "Hack", style = "Bold"}
italic = { family = "Hack", style = "Italic"}
bold_italic = { family = "Hack", style = "Bold Italic"}
size = 6 
offset                = { x = 0, y = 1 }
glyph_offset          = { x = 0, y = 0 }
builtin_box_drawing   = true

[window]
opacity = 0.4

[terminal.shell]
program = "/usr/bin/tmux"

[env]
TERM = "alacritty"
